Add required argument

diff --git a/1.8-gradle/test/run b/1.8-gradle/test/run
--- a/1.8-gradle/test/run
+++ b/1.8-gradle/test/run
@@ -9,6 +9,11 @@
 # IMAGE_NAME specifies a name of the candidate image used for testing.
 # The image has to be available before this script is executed.
 #
+if [ $# -eq 0 ]; then
+  echo "ERROR: No test project name has been passed."
+  exit 1
+fi
+
 IMAGE_NAME=${IMAGE_NAME-s2i-java8-gradle-candidate}
 
 # Determining system utility executables (darwin compatibility check)
diff --git a/1.8-maven/test/run b/1.8-maven/test/run
--- a/1.8-maven/test/run
+++ b/1.8-maven/test/run
@@ -9,6 +9,11 @@
 # IMAGE_NAME specifies a name of the candidate image used for testing.
 # The image has to be available before this script is executed.
 #
+if [ $# -eq 0 ]; then
+  echo "ERROR: No test project name has been passed."
+  exit 1
+fi
+
 IMAGE_NAME=${IMAGE_NAME-s2i-java8-maven-candidate}
 
 # Determining system utility executables (darwin compatibility check)
@@ -30,7 +35,6 @@ cid_file=$($MKTEMP_EXEC -u --suffix=.cid)
 s2i_args="--pull-policy=never --loglevel=2"
 
 # Port the image exposes service to be tested
-test_image_port="$(docker inspect --format='{{range $key, $value := .ContainerConfig.ExposedPorts }}{{$key}}{{end}}' ${IMAGE_NAME})"
 test_port="$(docker inspect --format='{{range $key, $value := .ContainerConfig.ExposedPorts }}{{$key}}{{end}}' ${IMAGE_NAME} | sed 's/\/.*//')"
 
 image_exists() {
